// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	integron "github.com/ganvoa/biopipe-tools/internal/integron"
	mock "github.com/stretchr/testify/mock"
)

// IntegronPersister is an autogenerated mock type for the IntegronPersister type
type IntegronPersister struct {
	mock.Mock
}

// Save provides a mock function with given fields: _a0
func (_m *IntegronPersister) Save(_a0 []integron.Integron) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func([]integron.Integron) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
