// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	integron "github.com/ganvoa/biopipe-tools/internal/integron"
	mock "github.com/stretchr/testify/mock"
)

// IntegronRepository is an autogenerated mock type for the IntegronRepository type
type IntegronRepository struct {
	mock.Mock
}

// AddIntegron provides a mock function with given fields: strainId, integrons
func (_m *IntegronRepository) AddIntegron(strainId int, integrons []integron.Integron) error {
	ret := _m.Called(strainId, integrons)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, []integron.Integron) error); ok {
		r0 = rf(strainId, integrons)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
