// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	strain "github.com/ganvoa/biopipe-tools/internal/strain"
	mock "github.com/stretchr/testify/mock"
)

// StrainRepository is an autogenerated mock type for the StrainRepository type
type StrainRepository struct {
	mock.Mock
}

// SaveAll provides a mock function with given fields: strains
func (_m *StrainRepository) SaveAll(strains []strain.Strain) error {
	ret := _m.Called(strains)

	var r0 error
	if rf, ok := ret.Get(0).(func([]strain.Strain) error); ok {
		r0 = rf(strains)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
